[io]
smiles_file = "/shared/morgan/MolScore_baselines/datasets/molopt/ZINC.smi"
model_file = "model.pt"

[network]
num_layers = 3
layer_sie = 512
dropout = 0.0
max_sequence_length = 256
cell_type = "gru"
embedding_layer_size = 256
layer_normalization = false
standardize = false

[metadata]